# Generated by Django 4.0.3 on 2022-04-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_rename_conductor_id_vehiculo_conductor'),
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.reparacion'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.servicio'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
    ]
