# Generated by Django 4.0.3 on 2022-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=70)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculos_id', models.CharField(max_length=60)),
                ('conductores_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.IntegerField(default=2021)),
                ('marca', models.CharField(max_length=30)),
                ('capacidad', models.IntegerField(default=20)),
                ('usuario_id', models.IntegerField(max_length=10)),
                ('conductor_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
