# Generated by Django 4.0.3 on 2022-04-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_capacidad_alter_vehiculo_conductor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='conductores_id',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='vehiculos_id',
        ),
        migrations.AddField(
            model_name='infraccion',
            name='conductor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='vehiculo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
