# Generated by Django 4.0.3 on 2022-04-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_remove_vehiculo_usuario_id_vehiculo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='conductor_id',
            new_name='conductor',
        ),
    ]
